2025-03-29 17:25:44,104 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-03-29 17:26:07,052 ERROR: Exception on /edit_profile [POST] [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\routes.py", line 96, in edit_profile
    return redirect(url_for('app.edit_profile'))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'app.edit_profile'. Did you mean 'edit_profile' instead?
2025-03-29 17:26:54,726 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
