2025-04-05 15:49:21,042 ERROR: Exception on /matches [POST] [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
        dialect, self, conn, execution_options, *args, **kw
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
    ...<2 lines>...
    )
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\routes.py", line 144, in matches
    db.session.commit()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str(statement), parameters, None, None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1812, in _execute_context
    context = constructor(
        dialect, self, conn, execution_options, *args, **kw
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 1477, in _init_compiled
    flattened_processors[key](compiled_params[key])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1116, in process
    raise TypeError(
    ...<2 lines>...
    )
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO "match" (opponent, location, timestamp) VALUES (?, ?, ?)]
[parameters: [{'opponent': 'opponent1', 'location': 'location1', 'timestamp': ''}]]
2025-04-05 15:51:17,722 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
