2025-04-05 15:51:20,605 ERROR: Exception on /matches [POST] [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\routes.py", line 138, in matches
    match_date = datetime.strptime(form.date.data, "%Y-%m-%d")
  File "C:\Users\tenni\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 674, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 453, in _strptime
    raise ValueError("time data %r does not match format %r" %
                     (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
2025-04-05 15:54:49,057 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 15:55:13,475 ERROR: Exception on /matches [POST] [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\routes.py", line 149, in matches
    return render_template("matches.html", match=match, matches=matches, form=form)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\templates\matches.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\templates\base.html", line 32, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\templates\matches.html", line 38, in block 'content'
    <td><img src="{{ match.author.avatar(36) }}" alt="user profile image"></td>
    ^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.Match object' has no attribute 'author'
2025-04-05 16:07:13,817 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 16:08:54,896 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 16:10:07,284 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 16:46:38,243 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 17:26:32,050 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 17:26:35,532 ERROR: Exception on /matches [GET] [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\routes.py", line 150, in matches
    return render_template(
        "matches.html", title="Matches", matches=matches, form=form
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\templates\matches.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\templates\base.html", line 32, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\templates\matches.html", line 33, in block 'content'
    <a href="{{ url_for('match_details', id=match.id) }}">{{ match.opponent }}</a>
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'match_details' with values ['id']. Did you mean 'matches' instead?
2025-04-05 17:27:17,273 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
2025-04-05 17:28:51,462 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
